app/models.py
from . import db
from datetime import datetime
from app import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader 
def load_user(user_id):
  return User.query.get(int(user_id)) 

class User(db.Model, UserMixin): 

  __tablename__='users'

  id = db.Column(db.Integer, primary_key = True) 
  username = db.Column(db.String(20), unique=True, nullable=False)
  email = db.Column(db.String(120), unique=True, nullable =False)
  password = db.Column(db.String(120), nullable =False)
  created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  blog_posts = db.relationship('BlogPost', backref = 'author', lazy='dynamic')
  comments  = db.relationship('Comment', backref='author', lazy='dynamic')

  def __repr__(self):
    return(f"User('{self.username}', '{self.email}')")

class BlogPost(db.Model):

  __tablename__='blogposts'
  
  id = db.Column(db.Integer, primary_key = True)
  title = db.Column(db.String(200), nullable = False)
  created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  content = db.Column(db.Text, nullable=False)
  category = db.Column(db.String(200), nullable = False)
  image_file = db.Column(db.String(120), nullable =True, default='default.jpg')
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
  comments = db.relationship('Comment', backref='blog_post', cascade='all, delete-orphan', lazy='dynamic')


class Comment(db.Model):

  __tablename__='comments'

  id = db.Column(db.Integer, primary_key = True)
  content = db.Column(db.Text, nullable=False)
  created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
  blogpost_id = db.Column(db.Integer, db.ForeignKey('blogposts.id'), nullable=False)

class Quotes:

  def __init__(self, id, author, quote):
    self.id = id
    self.author = author
    self.quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from app.models import User


class NewPost(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  content = TextAreaField('Content', validators=[DataRequired()])
  category = SelectField('Category', choices=[('music','Music'), ('fashion','Fashion'), ('entertainment','Entertainment'), ('art','Art'), ('workout','Workout'), ('health','Health')], validators=[DataRequired()])
  image_file =FileField('Upload Picture', validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'])])
  submit = SubmitField('Post')


class CommentForm(FlaskForm):
	content = TextAreaField('Add comment', validators=[DataRequired()])
	submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_mail import Mail
# from flask_simplemde import SimpleMDE
from config import config_options

db = SQLAlchemy() #instance of the db
login_manager = LoginManager()
bcrypt = Bcrypt()
mail = Mail()
# simple = SimpleMDE()

 

def create_app(config_name):
  app = Flask(__name__)
  app.config.from_object(config_options[config_name])

  #intializing extensions
  db.init_app(app)
  login_manager.init_app(app)
  bcrypt.init_app(app)
  mail.init_app(app)
  # simple.init_app(app)

  #Registering blueprints
  from .main import main
  app.register_blueprint(main)

  
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

  return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__) 

from . import views, errors

app/main/views.py
import markdown2
from flask import render_template, redirect, url_for, request, flash, abort
from flask_login import current_user, login_required
from app.models import BlogPost, User, Comment
from app.requests import get_quotes
from .forms import NewPost, CommentForm
from .utils import save_blog_picture
from . import main
from app import db
from app.email import subscription_email


@main.route('/')
@main.route('/home')
def index():

  quotes = get_quotes()

  blogpost = BlogPost.query.filter().order_by(BlogPost.created_at.desc())

  return render_template('index.html', title = 'Welcome to MyBlog', blogposts=blogpost, quotes=quotes)

@main.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():

  form = NewPost()

  if form.validate_on_submit():
    picture_file = ''
    if form.image_file.data == None:
      picture_file = 'default.jpg'
    else:
      picture_file =  save_blog_picture(form.image_file.data)
    post = BlogPost(title=form.title.data, content=form.content.data, category=form.category.data, author=current_user, image_file=picture_file)
    db.session.add(post)
    db.session.commit()

    users = User.query.all()
    for user in users:
      if user.email != current_user.email:
        subscription_email("New Post Alert", "email/new_post_subscription", user.email, user=user)

    flash('Your post has been created!', 'success')
    return redirect(url_for('.index'))
  return render_template('create_post.html', title='New Post Blog', form=form, legend='New Post')

@main.route('/post/<blogpost_id>', methods=['GET', 'POST'])
def post( blogpost_id):
  post = BlogPost.query.get_or_404(blogpost_id) #fetching post from database by id
  form =  CommentForm()
  if form.validate_on_submit():
    comment = Comment(content=form.content.data, author=current_user,  blogpost_id =  blogpost_id)
    db.session.add(comment)
    db.session.commit()
    flash('Your comment has been posted!', 'success')
    return redirect(url_for('.post',  blogpost_id= blogpost_id))
    
  all_comments = Comment.query.filter_by( blogpost_id= blogpost_id).all()

  return render_template('post_detail.html', title=post.title, post=post, legend='Leave a Comment', form=form, comments=all_comments)

@main.route('/post/<int:blogpost_id>/update', methods=['GET', 'POST'])
@login_required
def update_post( blogpost_id):

  post = BlogPost.query.get_or_404( blogpost_id)

  if post.author != current_user:
    abort(403)
  form = NewPost()
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit()
    flash('Your blog post has been updated', 'success')
    return redirect(url_for('.index', blogpost_id= blogpost_id))
  elif request.method == 'GET':
    form.title.data = post.title
    form.content.data = post.content
  return render_template('create_post.html', title='Update Blog Post', form=form, legend='Update Post',  blogpost_id= blogpost_id)

@main.route('/post/<int:blogpost_id>/delete', methods=['POST'])
@login_required
def delete_post(blogpost_id):
  post = BlogPost.query.get_or_404(blogpost_id)
  if post.author != current_user:
    abort(403)
  db.session.delete(post)
  db.session.commit()
  flash('Your post has been deleted', 'success')
  return redirect(url_for('.index'))

@main.route('/post/<int:blogpost_id>/comments/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(blogpost_id, comment_id):
  post = BlogPost.query.get_or_404(blogpost_id)
  print(current_user.id)
  
  if post:
    comment = Comment.query.get_or_404(comment_id)
    print(comment.user_id)
    if comment.user_id == current_user.id or post.author == current_user.id:
      
      db.session.delete(comment)
      db.session.commit()
      flash('Your comment has been deleted', 'success')
      return redirect(url_for('.post', blogpost_id= blogpost_id))
    else:
      abort(403)

app/templates/about.html
{% extends "layout.html" %}

{% block content %}
    <h1>About us page</h1>
{% endblock content %}

   

app/templates/article.html
<article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ post.author }}</a>
        <small class="text-muted">{{ post.date_posted }}</small>
      </div>
      <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,600&family=Noto+Serif&family=Permanent+Marker&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="../static/css/main.css">
  {% if title %}
  <title> {{ title }}</title>
  {% else %}
  <title> Welcome to MyBlog </title>
  {% endif %}
</head>

<body>

  <!-- Navbar block-->
  {% block navbar %}
  {% include 'navbar.html' %}
  {% endblock navbar %}

  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}}">
      {{ message }}
    </div>
    {% endfor %}

    {% endif %}
    {% endwith %}
  </div>


  <!--Content block-->
  {% block content %}

  {% endblock content %}



  <footer class="page-footer">
    <div class="footer-copyright text-center">
      <h6>© 2022 Copyright: Chepngetich Edah</h6>
    </div>
  </footer>



  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>

</html>

app/templates/carousel.html
<div class="container">
  <div class="row">
    <div class="card">
      <div id="quotes" class="carousel slide text-center" data-ride="carousel" id="carousel" style="background-color: #06313f; padding: 0; margin:0; color:#ffffff">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <h5 class="mt-3 text-success">{{quotes.quote}}</h5>
            <p>{{quotes.author}}~</p>
          </div>
          <div class="carousel-item">
            <h5 class="mt-3 text-success">{{quotes.quote}}</h5>
            <p>~ {{quotes.author}}~ </p>
          </div>
          <div class="carousel-item">
            <h5 class="mt-3 text-success">{{quotes.quote}}</h5>
            <p>~ {{quotes.author}}~ </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
    <title> contact {% title %} </title>
    {% else %}}
    <title>contact</title>
</head>
<body>
    {% blockcontent %}
    {% endblock %}
</body>
</html>

app/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="card new-post">
        <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4"> {{ legend }}</legend>
            <div class="form-group">
              {{ form.title.label (class="form-control-label") }}
              {% if form.title.errors %}
              {{ form.title(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.title (class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.content.label (class="form-control-label") }}
              {% if form.content.errors %}
              {{ form.content (class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.content.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.content (class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.category.label (class="form-control-label") }}
              {% if form.category.errors %}
              {{ form.category (class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.category.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} 
              {{ form.category (class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.image_file.label () }}
              {{ form.image_file (class="form-control-file image") }}
              {% if form.image_file.errors %}
                {% for error in form.image_file.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %}
              {% endif %}
            </div>
          </fieldset>
          <div class="form-group">
            {{ form.submit (class="btn btn-outline-info") }}
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

{% endblock content %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<body class="blogs">
  <div id="quotes" class="carousel slide text-center" data-ride="carousel" style="background-color: #30E3CA;">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <h5 class="mt-3 text-success">{{quotes.quote}}</h5>
        <p>{{quotes.author}}~</p>
      </div>
      <div class="carousel-item">
        <h5 class="mt-3 text-success">{{quotes.quote}}</h5>
        <p>~ {{quotes.author}}~ </p>
      </div>
      <div class="carousel-item">
        <h5 class="mt-3 text-success">{{quotes.quote}}</h5>
        <p>~ {{quotes.author}}~ </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="demo">
      {% for post in blogposts %}
      <div class="card posts" style="width: 18rem;">
        <img class="card-img-top" src="../static/images/blog_pictures/{{ post.image_file }}" alt="{{ post.title }}"
          width="18rem" height="200px">
        <div class="card-body">
          <h5 class="title" style="font-weight: bold;">{{ post.title }}</h5>
          <a href="{{ url_for('.post', blogpost_id=post.id)}}" class="btn btn-primary">Read More</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  </div>
</body>




{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{{url_for ('static' ,filename = 'main.css')}}" type="text/css" media="all">
    {% if title %}
    <title>flask-blog-{{ title}}</title>
    {% else %}
    <title>flask-blog</title>
    {% endif %}
</head>
<body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/">Home</a>
                    <a class="nav-item nav-link" href="/about">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/login">Login</a>
                    <a class="nav-item nav-link" href="/register">Register</a>
                </div>
                </div>
            </div>
            </nav>
        </header>
      

        <main role="main" class="container">
            <div class="row">
              <div class="col-md-8">
                {% block content %}{% endblock %}
              </div>
              <div class="col-md-4">
                <div class="content-section">
                  <h3>Our Sidebar</h3>
                  <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                      <li class="list-group-item list-group-item-light">Latest Posts</li>
                      <li class="list-group-item list-group-item-light">Announcements</li>
                      <li class="list-group-item list-group-item-light">Calendars</li>
                      <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                  </p>
                </div>
              </div>
            </div>
          </main>
          

    
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

   

app/templates/macros.html
{% macro displayCategoryList(category_list) %}
    {% for category in category_list%}
        <div>
          <p>{{category.category_title|upper}}</p>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="mb-1 navbar navbar-expand-lg navbar-dark  #212121 grey darken-4">
  <a class="navbar-brand" href="{{ url_for('main.index')}}">Favourite Posts</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.index') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fa fa-facebook"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fa fa-twitter"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fa fa-instagram"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect waves-light">
          <i class="fab fa-google-plus-g"></i>
        </a>
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.new_post') }}">Create a Post</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth.register') }}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth.login') }}">Log in</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

app/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}

<body class="blogs">
  <div class="container">

    <div class="media">
      <img src="../static/images/blog_pictures/{{ post.image_file }}" class="mr-3" alt="{{ post.title }}" width="400px"
        height="350px">
      <div class="media-body">
        <h5 class="mt-0 title"><b>{{ post.title }}</b></h5>
        <h6 class="mt-0">Published by: {{ post.author.username }} <span style="float: right;">On:
            {{ post.created_at.strftime('%Y/%m/%d')}}</span></h6>
        <p>{{post.content}}</p>
      </div>
    </div>
    {% if post.author == current_user %}
    <div>
      <a href="{{ url_for('.update_post',  blogpost_id=post.id)}}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
      <button type="button" class="btn btn-danger btn-sm ml-1" data-toggle="modal"
        data-target="#deleteModal">Delete</button>
    </div>
    {% endif %}

  <div class="comment">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4"> {{ legend }} </legend>
        <div class="form-group">
      
          {% if form.content.errors %}
          {{ form.content (class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.content.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.content (class="form-control form-control-lg content-form") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit (class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
  <div class="comments">
    {% if comments %}
    {% for comment in comments %}
    <div class="card">
      <article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ comment.author.username }}</a>
            <small class="text-muted">{{ comment.created_at.strftime('%Y/%m/%d')}}</small>
          </div>
          <p class="article-content">{{ comment.content }}</p>
          <button type="button" class="btn btn-danger btn-sm ml-1" data-toggle="modal"
            data-target="#deleteModal{{ comment.id }}">Delete</button>
        </div>
      </article>
    </div>

    <div class="modal fade" id="deleteModal{{ comment.id }}" tabindex="-1" role="dialog"
      aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this comment?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"
              style="float: right; margin-left: 15px;">Close</button>
            <form action="{{ url_for('.delete_comment', comment_id=comment.id, blogpost_id=post.id) }}" method="POST">
              <input type="submit" class="btn btn-danger" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
    {% else %}
    <p> This post has no comments yet</p>
    {%endif%}
  </div>
  </div>

  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"
            style="float: right; margin-left: 15px;">Close</button>
          <form action="{{ url_for('.delete_post', blogpost_id=post.id) }}" method="POST">
            <input type="submit" class="btn btn-danger" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

</body>


{% endblock content %}

app/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}